2 resz
rrd108/youtube-modern-php pull request #1
Opened 2021-08-15 11:46 UTC by Attilius

Hello rrd!

Lelkes PHP rajongóként felkeltette érdeklődésem a szavazó alkalmazásod, amit néhány napja láttam youtube-on. Így vettem a bátorságot és le forkoltam, majd eszközöltem rajta néhány változtatást. Nézzd át s ha gondolod merge-lheted a változásokat az eredezi applikációba. Amúgy két változatot is készítettem belőle, az első még a gépemen van. Abban a százalékértékek előtt lévő szíveket az adott frontend keretrendszer ikonjára cseréltem le, aminek az elérési útvonalát tömbben adtam meg a szavazatszám mellett, így dinamikusan azt is megjeleníti. Ez csak némi design változtatás volt, ha gondolod elkészíthetem erre a verzióra is. Eme második verzióban a szíveket meghagytam, viszont úgy gondoltam a szívek színei lehetnének dinamikusak az adott százalékok függvényében. Tudom ezt frontend-ben kellene megoldani, de a PHP erre is ad módot! :) Továbbá egy kisebb bug-ot is találtam még az első nekifutás alkalmával, miszerint az oldal frissítésekor ha már történt szavazatleadás, akkor a böngészőben "bentragad" az információ, így újra és újra elküldi ugyan azt, ha nyomunk egy F5-öt. Ezt itt is javítottam, egy header-be küldött üzenettel, valamint a $_POST küldéseket "isset()"-be tettem, így egy óvatlan küldés nem eredményez nemlézető üres string hibát. Két függvénnyel is gyarapítottam a functions.php-t, ha már a neve többessámú akkor ne csak egy árválkodjon benne. :)  Kiszerveztem oda a százalékszámítást, mert picit más módon számoltam ki. Próbáltam 100-as pontosságnál maradni, de sajnos felugrik 101-re, viszont nem adom fel dolgozom az ügyön. A másik függvény a szívek színeit állítja dinamikusan, nyílván nem a legszebb megoldás amit kigondoltam rá, de majd finomítok azon is. A videóból lemaradt, de láttam egyedi adathozzáadást is tettél bele. Ehhez egy tömbbe összeszedtem néhány egyéb frontend keretrendszert, meg is lepett mennyi van. Így a hamis adatokat ki lehet szűrni, majd loggolni. Ha már itt tartok a hamis adatok illetve ip rögzítésén tovább dolgozom, meg a 666-os file jogosultság kérdésén is. Valmint motoszkál a gondolataimban egy automatikus file készítés, hogy minden napra jusson valami, így a dátumfüggvényt is élesíteni lehetne.  

Üdvözlettel: Attilius

ui.: Nagyon tetszenek a videóid youtube-on kifejezetten a PHP-sek, mert a PHP lett az egyik kedvencem. Frontend-ben pedig a Vue a favorit számomra. :) Várom a folytatásokat.

2021-08-16 08:20 UTC, rrd108 commented
Köszi, hamarosan átnézem.
A bugfix a harmadik részben lesz majd, épp tegnap vettem fel azt a részt :)

Valószínűleg majd megkérlek, hogy szedd szét a PR-t darabokra - majd megírom mikre, hogy mások is követni tudják, hogy mi micsoda.

Kis türelmet kérek sűrű 2 hét előtt állok.

2021-08-16 13:40 UTC, Attilius commented
Rendben!  Ahogy időd engedi, várom majd az instrukciókat. :) Szívesen segítek amiben tudok. Egyúttal ezzel is gyakorlok. Most picit nekem is sűrű lesz főleg ez a hét, mert egy C++/Java interjú előtt állok, így most nekem egy üde kis levezetés ez a PHP projekt. :) Egyébként most kódolom a logfájl kezelést, ha kamu adat érketik a frontend manupulálásából kifolyólag.

2021-09-04 07:57 UTC, rrd108 requested changes
Ezt a filet ne tedd bele, nincs benne kód változás, az adatok meg mindenkinél máshogy néznek majd ki.

2021-09-04 08:03 UTC, rrd108 commented
A functions.php jó így ahogy van.
A $possibleAnswers-t hagyjuk most ki, lehet erről lesz majd egy külön rész.
Az index.php-ben pedig közben bekerült a számolás fix, szóval azt is kiveheted.

2021-09-04 08:03 UTC, closed without merging